swagger: 2.0
info:
  title: Catalogus API
  version: 1.0
host: localhost
basePath: /catalogus/api/v1
produces:
  - text/plain
paths:
  /id/concept:
    get:
      x-dotwebstack-information-product: "http://localhost:8080/catalogus/dso#Concepten"
      responses:
        200:
          description: OK
    post:
      x-dotwebstack-transaction: "http://localhost:8080/catalogus/dso#ConceptPOST"
      responses:
        200:
          description: OK
    put:
      x-dotwebstack-transaction: "http://localhost:8080/catalogus/dso#ConceptPUT"
      responses:
        200:
          description: OK
  /id/concept/{id}:
    get:
      x-dotwebstack-information-product: "http://localhost:8080/catalogus/dso#Concept"
      responses:
        200:
          description: OK
