swagger: 2.0
info:
  title: DBeerPedia API
  version: 1.0
host: %{dotwebstack.config.host}
basePath: /dbp/api/v1
produces:
  - application/json
paths:
  /breweries:
    get:
      x-dotwebstack-information-product: "http://dbeerpedia.org#TupleBreweries"
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
# inline with provided example data
                naam:
                  type: string
                  format: string
  /brewery/{id}:
    get:
      x-dotwebstack-information-product: "http://dbeerpedia.org#TupleBrewery"
      parameters:
      - name: id
        in: path
        description: Identifier
        required: true
        type: string
        x-dotwebstack-parameter: "http://dbeerpedia.org#IdFilter"
      responses:
        200:
          description: OK
          schema:
            type: object
# inline with provided example data
            required:
              - naam
# inline with provided example data
            properties:
              naam:
                type: string
                format: string
              website:
                type: string
                format: string
              kvk:
                type: string
                format: string
              sinds:
                type: integer
                format: int32
              provincie:
                type: string
                format: string
