language: java
jdk:
  - oraclejdk8
notifications:
  slack:
    secure: K1SjU2mgGbbA9M2gyDRKDOtdmyLcl+ahNIlxSLWNI76IT9iRyw2djsGPoDcaXKYuEFQXpJ4VISzxhM140HBIvAQg5aj/kNS6tpZ+HpZzL7kZHQf9BlvLSFXSJ6CZXuny+K7ToQpwF+MIuIyOWHlRdhlQgB3FVVCu15aJIPwVD7JcW2n4Zo9Kwu2g3V1a2IvC3gESaLr7UWb3rbu+pFAANAHz8oBBy0RYN4bYtumyvDzyE5n5iO+NzzBUb2M6c+8WvkOj2DivZMaj8Vf4gHKsvtTY+HhwN9dxxtBGMjswVRKeQHLZ3wv8SjV5hLpvBW2j3MPiMlRpxlDOS5ItfD5NU8/KPcMRIuiGNauf1TKSUprQlcWcaOgYIGP+hjklwXX4xx27InwBK9OJVQl88bd7w9Ujn2MiqvujkUB4gKr1nVmR0264YWCfjI0+pLakCNfHoin6CyKl+L0RuvjkvqarbJY7b1uZujViAOvaGZuHJ3awGQi2D2UFgMGpz4hTe5SASMbK9YmVOR7O/9FvxBI45BzYE9ix6SbPadxMdKiCo1RVrZkk4QV8c9XT0tqnHBUPuSpC+VBHBx1NdYzG71WVfHzFgNsUFrRAlOCcElql9zOoQCrsSb+QzhjHu8QWdyXA2Vip15sUSs4tq/EbSE0qIBXM0qX3IDgZ1Fty3q2NY/M=
