spring:
  main:
    banner-mode: "off"
  jersey:
    type: filter

logging.level:
  org.dotwebstack.framework: DEBUG
  org.springframework.boot.autoconfigure.logging: INFO

dotwebstack:
  config:
    resourcePath: file:src/main/resources
    host: localhost
    systemGraph: http://dbeerpedia.org#Theatre
