spring:
  main:
    banner-mode: "off"
  jersey:
    type: filter

logging.level:
  org.dotwebstack.framework: DEBUG

dotwebstack:
  config:
    resourcePath: file:src/main/resources
    host: localhost
    systemGraph: http://dbeerpedia.org#Theatre