spring:
  main:
    banner-mode: "off"
  jersey:
    type: filter
  resources:
    static-locations: file:src/main/resources/static/,classpath:/static/

logging.level:
  org.dotwebstack.framework: DEBUG

dotwebstack:
  config:
    resourcePath: file:src/main/resources
    host: localhost
    linkstrategy: global
    systemGraph: http://dbeerpedia.org#Theatre
