spring:
  main:
    banner-mode: "off"
  jersey:
    type: filter

logging.level:
  org.dotwebstack.framework: DEBUG

dotwebstack:
  config:
    host: localhost
    resourcePath: file:src/main/resources
    systemGraph: http://dotwebstack.org/configuration/SandboxTheatre
